apiVersion: v1
kind: Service
metadata:
  name: polaris-postgres
  labels:
    app.kubernetes.io/name: polaris-postgres
spec:
  type: ExternalName
  externalName: {{ printf "polaris-postgres-rw.%s.svc.cluster.local" .Release.Namespace | quote }}
  ports:
    - name: postgres
      port: 5432
