"""MinHash signature compute.

Primary backend: Rensa (``rensa`` PyPI wheel, Rust core). 16-40x faster
signature compute than pure-Python datasketch on the FineWeb dataset.

Fallback: ``datasketch.MinHash``. The fallback is documented in the silver
record's ``extracted_with`` style ``backend`` field so the LSHBloom operator
can refuse to mix signatures generated by different backends (the byte
layout differs).

Stream2Pretrain uses 112 permutations - the FineWeb default - tuned for a
band/row layout of 28 bands x 4 rows giving a Jaccard threshold around 0.85.
"""

from __future__ import annotations

import hashlib
import re
from dataclasses import dataclass

DEFAULT_NUM_PERMS: int = 112
DEFAULT_NGRAM_SIZE: int = 5

_WORD = re.compile(r"\w+", re.UNICODE)


def shingle(text: str, *, n: int = DEFAULT_NGRAM_SIZE) -> list[str]:
    """Word-level n-gram shingles (whitespace-tokenised, case-folded)."""
    tokens = [t.lower() for t in _WORD.findall(text)]
    if len(tokens) < n:
        return [" ".join(tokens)] if tokens else []
    return [" ".join(tokens[i : i + n]) for i in range(len(tokens) - n + 1)]


@dataclass(frozen=True, slots=True)
class MinHashSignature:
    """Result returned by :meth:`MinHasher.signature`."""

    digest: bytes
    num_perms: int
    backend: str

    def band_keys(self, num_bands: int = 28) -> list[bytes]:
        """Slice the digest into ``num_bands`` band keys for LSH banding."""
        if self.num_perms % num_bands != 0:
            raise ValueError(
                f"num_perms ({self.num_perms}) must divide num_bands ({num_bands})"
            )
        rows = self.num_perms // num_bands
        # Each permutation is 4 bytes (uint32). Reslice into bands.
        chunk = rows * 4
        return [self.digest[i * chunk : (i + 1) * chunk] for i in range(num_bands)]


class MinHasher:
    """MinHash signature wrapper with Rensa primary / datasketch fallback."""

    def __init__(
        self,
        *,
        num_perms: int = DEFAULT_NUM_PERMS,
        ngram_size: int = DEFAULT_NGRAM_SIZE,
        seed: int = 0xC0FFEE,
    ) -> None:
        if num_perms <= 0 or num_perms % 4 != 0:
            raise ValueError("num_perms must be a positive multiple of 4")
        self._num_perms = num_perms
        self._ngram_size = ngram_size
        self._seed = seed
        self._impl, self._backend = self._load_backend()

    @property
    def num_perms(self) -> int:
        return self._num_perms

    @property
    def backend(self) -> str:
        return self._backend

    def _load_backend(self) -> tuple[object, str]:
        try:
            from rensa import RMinHash  # type: ignore[import-untyped]

            return RMinHash, "rensa"
        except Exception:
            pass
        try:
            from datasketch import MinHash  # type: ignore[import-untyped]

            return MinHash, "datasketch"
        except Exception:
            return None, "fallback-pyhash"  # type: ignore[return-value]

    def signature(self, text: str) -> MinHashSignature:
        """Compute the signature for ``text``."""
        shingles = shingle(text, n=self._ngram_size)
        if self._backend == "rensa":
            return self._signature_rensa(shingles)
        if self._backend == "datasketch":
            return self._signature_datasketch(shingles)
        return self._signature_python(shingles)

    def _signature_rensa(self, shingles: list[str]) -> MinHashSignature:
        rminhash_cls = self._impl
        m = rminhash_cls(num_perm=self._num_perms, seed=self._seed)
        m.update(shingles)
        digest = bytes(m.digest())  # rensa returns bytes-like uint32 array
        return MinHashSignature(digest=digest, num_perms=self._num_perms, backend="rensa")

    def _signature_datasketch(self, shingles: list[str]) -> MinHashSignature:
        minhash_cls = self._impl
        m = minhash_cls(num_perm=self._num_perms, seed=self._seed)
        for s in shingles:
            m.update(s.encode("utf-8"))
        # datasketch hashvalues is a numpy uint64 array; cast to uint32 LE.
        try:
            arr = m.hashvalues.astype("<u4")  # type: ignore[attr-defined]
            digest = arr.tobytes()
        except Exception:
            digest = b"".join(int(v).to_bytes(4, "little", signed=False) for v in m.hashvalues)
        return MinHashSignature(digest=digest, num_perms=self._num_perms, backend="datasketch")

    def _signature_python(self, shingles: list[str]) -> MinHashSignature:
        """Pure-Python deterministic MinHash for environments without wheels.

        The algorithm uses ``hashlib.blake2b`` keyed by the permutation index
        to derive ``num_perms`` independent hash functions. Deterministic
        and seeded, but ~50x slower than rensa - never used in production.
        """
        out = bytearray(self._num_perms * 4)
        encoded = [s.encode("utf-8") for s in shingles] or [b""]
        for i in range(self._num_perms):
            min_h = 0xFFFFFFFF
            key = i.to_bytes(4, "little") + self._seed.to_bytes(8, "little", signed=False)
            for shingle_bytes in encoded:
                h = hashlib.blake2b(shingle_bytes, digest_size=4, key=key).digest()
                v = int.from_bytes(h, "little", signed=False)
                if v < min_h:
                    min_h = v
            out[i * 4 : (i + 1) * 4] = min_h.to_bytes(4, "little", signed=False)
        return MinHashSignature(
            digest=bytes(out), num_perms=self._num_perms, backend="fallback-pyhash"
        )
