---
auth:
  rootUser: stream2pretrain
  rootPassword: stream2pretrain-dev-key

mode: standalone
defaultBuckets: "bronze,silver,gold,decon-attestations,loki-chunks,loki-ruler,loki-admin,tempo,polaris-warehouse,s2p-bronze,s2p-silver,s2p-gold,s2p-decon"

persistence:
  enabled: true
  storageClass: local-path
  size: 10Gi

service:
  type: ClusterIP
  ports:
    api: 9000

metrics:
  serviceMonitor:
    enabled: true
    namespace: monitoring

resourcesPreset: micro
