---
replicaCount: 1

image:
  repository: apache/polaris
  tag: "1.7.0"
  pullPolicy: IfNotPresent

persistence:
  type: relational-jdbc
  relationalJdbc:
    secret:
      name: polaris-persistence
      username: username
      password: password
      jdbcUrl: jdbcUrl

advancedConfig:
  quarkus.datasource.jdbc.min-size: "2"
  quarkus.datasource.jdbc.max-size: "10"
  quarkus.datasource.jdbc.acquisition-timeout: "30S"
  quarkus.datasource.jdbc.idle-removal-interval: "5M"

realmContext:
  type: default
  realms: [POLARIS]
  requireHeader: false

extraEnv:
  - name: QUARKUS_HTTP_HOST
    value: "::"
  - name: QUARKUS_MANAGEMENT_HOST
    value: "::"
  - name: POLARIS_BOOTSTRAP_CREDENTIALS
    valueFrom:
      secretKeyRef:
        name: polaris-root-identity
        key: credentials
  - name: AWS_ACCESS_KEY_ID
    valueFrom:
      secretKeyRef:
        name: polaris-minio
        key: accessKey
  - name: AWS_SECRET_ACCESS_KEY
    valueFrom:
      secretKeyRef:
        name: polaris-minio
        key: secretKey
  - name: AWS_REGION
    value: us-east-1

serviceMonitor:
  enabled: true
  labels:
    release: kube-prometheus-stack
