image:
  repository: postgres
  tag: "17.6-alpine"
  pullPolicy: IfNotPresent

credentialsSecret: polaris-persistence

persistence:
  storageClass: local-path
  size: 5Gi

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: "1"
    memory: 1Gi

